# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install webpack
        run: npm install
      - name: npm build webpack
        run:  npm run build
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
      with: 
        name: webpack artifacts
        path: public
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: npm test
      run: npm test
      env:
        CI: true
